# Generated by Django 4.2.30 on 2026-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_weatherrecord_delete_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
